### PR TITLE
New release 

### PR DESCRIPTION
**Pull request by ChoboHub**
Added a lot of new traduction for french users

### CODE REVIEW

**Comment by bpierre** [comment]
Merged, thanks. I am not really using Symphony CMS anymore, would you be interested to take ownership of the project?

**Comment by ChoboHub** [comment]
My pleasure, you could give the ownership to @nitriques. I'm working under his wings.
Thanks for the fast merge!

**Comment by bpierre** [comment]
Commit access granted to both of you. :-)

**Comment by ChoboHub** [comment]
Thank you :)

**Pull request merged**
